name: github-actions-dotnet-webapp

on:
  push:
    branches: [ "main" ]
  # schedule:
  #    - cron: '0 * * * *'  # Executa a cada hora
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
          echo "Restaurando dependências..."
          dotnet restore **/*.csproj

      - name: Build
        run: |
          echo "Compilando projeto..."
          dotnet build **/*.csproj --no-restore
